<input name="cmdper" id="cmdper" type="submit" value="Empleados" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_empleados_main.php'; document.form1.submit()" /> 
<input name="cmdnov" id="cmdnov" type="submit" value="Asistencias" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_asistencias_main.php'; document.form1.submit()" /> 
<input name="cmdliq" id="cmdliq" type="submit" value="Horarios" onclick="javascript: document.form1.target='_self'; document.form1.action='horarios_main.php'; document.form1.submit()" /> 
<input name="cmdliq" id="cmdliq" type="submit" value="Ingresos" onclick="javascript: document.form1.target='_self'; document.form1.action='ingresos_main.php'; document.form1.submit()" /> 
<input name="cmdade" id="cmdade" type="submit" value="Adelantos" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_adelantos_main.php'; document.form1.submit()" /> 
<input name="cmdext" id="cmdext" type="submit" value="Extras" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_extras_main.php'; document.form1.submit()" /> 
<input name="cmdsal" id="cmdsal" type="submit" value="Saldos" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_saldos_main.php'; document.form1.submit()" /> 
<input name="cmdliq" id="cmdliq" type="submit" value="Liquidaciones" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_liquidacion_main.php'; document.form1.submit()" /> 
<input name="cmdliq" id="cmdliq" type="submit" value="Sueldos" onclick="javascript: document.form1.target='_self'; document.form1.action='adm_sueldo_main.php'; document.form1.submit()" /> 
<input name="cmddep" id="cmddep" type="submit" value="Departamentos" onclick="javascript: document.form1.target='_self'; document.form1.action='departamento_main.php'; document.form1.submit()" /> 
